### ISSUE TITLE
Wrong ground truth example

### ISSUE THREAD

**Issue by stweil** [OCR4all/getting_started#1]
[ocr4all-user_guide_ger.pdf](https://github.com/OCR4all/getting_started/blob/master/ocr4all-user_guide_ger.pdf) and also the other user guides show wrong ground truth for menu entry "Ground Truth Production". It should be "Circassiern und Arabern".

Is the source code for the PDF files also available? Then it would be easier to contribute more typo and grammar fixes.

**Comment by chreul** [comment]
Thanks for the remark but I kinda fail to locate it. In Abb. 7 it says "Eircassiern und ...". However, that isn't GT but just a (slightly flawed) uncorrected OCR output. A corrected output would be colored green. Abb. 38 Ground Truth Production then shows a different example and the GT seems correct to me.
Am I missing something? :-)

**Comment by stweil** [comment]
Abb. 7 was the location I was referring to. I misinterpreted it as GT, sorry. So this issue can be closed.

My additional question regarding how to contribute typo and grammar fixes still applies.

**Comment by chreul** [comment]
The sources are now available. Sorry for the delay and thanks for any future contributions.
