### ISSUE TITLE
Instalation Problem

### ISSUE THREAD

**Issue by NishinoTSK** [OCR4all/getting_started#11]
I instaled OCR4all in virtual machine following the guide "ocr4all_setup_guide_virtualbox_eng" but i cant but I can't get past the login screen. Any tips?
![Screen](https://user-images.githubusercontent.com/53551043/121829351-a0373500-cc98-11eb-9ab9-3926203334fc.png)

**Comment by maxnth** [comment]
Hi, the login prompt may be a bit confusing as logging in isn't necessary to get OCR4all up and running.
As soon as the Ubuntu login prompt appears, OCR4all should already reachable (this may also take a few minutes depending on the resources allocated to the virtual box) on the host machine if the port forwarding is set up correctly.
In case you want to login anyways the default credentials are `ocr4all:ocr4all`. These should get changed if the virtual box is reachable from outside your host.

I just opened an issue (https://github.com/OCR4all/vbox_install/issues/3) regarding adding more concrete information to the state of the OCR4all instance in a future release.

**Comment by maxnth** [comment]
Feel free to reopen this issue or create a new one in case any further problems with the VirtualBox arise.
