### ISSUE TITLE
Documentation could be improved

### ISSUE THREAD

**Issue by hannesa2** [OCR4all/getting_started#12]
Without checking it out and read it in github direct
* either documentation is not readable (doxc)
* or you can't copy anything from the given pdf

**Comment by maxnth** [comment]
Thanks for the issue and PR. 
I fully agree that a markdown (or something similar) based approach would be a lot more suitable for the documentation as it would make managing history, editing regardless of OS / office suite, etc. a lot more streamlined.
We already looked into rewriting / updating the docs and using a markdown to static site generator (Jekyll, mkdocs, etc.) to make the docs more accessible but sadly didn't find the time for it yet.

I guess the best short term solution would be merging your .md files but still keeping the PDF files as we have a lot of non-technical users who'd probably still prefer using PDF. 
What do you think @maxwehner ?
