### ISSUE TITLE
Are the titles pre-loaded automatically?

### ISSUE THREAD

**Issue by anatexis** [OCR4all/getting_started#15]
I was confused about the [setup-guide](https://www.ocr4all.org/guide/setup-guide/linux), I assumed the two books ("Cirurgia" and "GNM") are included in the docker image, but I assume one has to manually download them from github to the ocr4all/data folder?
I think this could be made clearer in the guide -- I didn't find a github repo or I would have proposed a change there.

**Comment by maxnth** [comment]
>but I assume one has to manually download them from github to the ocr4all/data folder?

You're right, this is indeed confusing. We'll change this in the docs to make it clearer.

>I didn't find a github repo or I would have proposed a change there.

The repository for the documentation website can be found [here](https://github.com/OCR4all/OCR4all.github.io)

**Comment by anatexis** [comment]
Thank you!

**Comment by maxnth** [comment]
Updated documentation in [5427a61](https://github.com/OCR4all/OCR4all.github.io/commit/5427a61c325a632fddd1a411a89675d59a9ea1e3)
