### ISSUE TITLE
cannot map root to user

### ISSUE THREAD

**Issue by tango2** [OCR4all/getting_started#2]
Hello,
Trying to get this docker image running under Ubuntu. When I use:
sudo docker run -p 1476:8080 -p 5000:5000 -u 'id -u root':'id -g $USER' --name ocr4all -v $PWD/data:/var/ocr4all/data -v $PWD/models:/var/ocr4all/models/custom -it ls6uniwue/ocr4all

I get:
docker: Error response from daemon: unable to find user id -u root: no matching entries in passwd file.

Any ideas on how to fix this?

**Comment by ChWick** [comment]
You need to use a grave accent:
```
`
```
not
```
'
```

**Comment by Kolophonium0** [comment]
Closing this issue. In case that this issue is not solved please comment again.
