### ISSUE TITLE
Can't load an existing project

### ISSUE THREAD

**Issue by kranatalie** [OCR4all/getting_started#4]
Hello,

I just installed OCR4all in Virtualbox using your guide, and I finally succeeded (I am working on Windows and I had to do a change in my BIOS settings to get the machine started).

So, finally I was able to open OCR4all in my browser (Chrome) but unfortunately I can't open any project there. It says in one of your guides on getting started that I should choose the project from the dropdown list, but there is no dropdown list available. Can anybody help me out?

The two examples GMN and and Cirurgia are downloaded. Maybe into the wrong folder?! Sorry for asking those questions, I am new to this.

![image](https://user-images.githubusercontent.com/60134778/84948004-67976680-b0eb-11ea-849f-96cab6816145.png)

**Comment by Kolophonium0** [comment]
Hey Kranatalie,
Don't worry, and keep on asking.
If the drop-down list is missing, there is a problem with the folder mapping. Can you go to the Vbox settings and post the paths here?

**Comment by kranatalie** [comment]
I just deleted the current installation and set it up all again - and now it works. I must have made a mistake before with the path, even I can't figure out which one. Anyways, thanks for being around!

**Comment by Kolophonium0** [comment]
Your welcome. Yeah the path setting is a critical step in creating these boxes your not alone with this. Feel free to contact us with any issues or suggestions you might have. We're always glad for user feedback.
