### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by svetlinsem** [OCR4all/getting_started#5]
Hello i try to install Ocr4all in Alibabacloud but every time i have this
![Screenshot_1](https://user-images.githubusercontent.com/6574903/85945459-88ab5300-b946-11ea-9a70-c4857673a5d8.png)
 [output.

**Comment by Kolophonium0** [comment]
Have you tried it without running it as root user?

**Comment by svetlinsem** [comment]
Yes, but no effect.
![Screenshot_2](https://user-images.githubusercontent.com/6574903/85945981-f73de000-b949-11ea-9c95-e6399c6b9c51.png)

**Comment by maxnth** [comment]
@svetlinsem The output in your first screenshot is the default output when a docker container of OCR4all is starting and nothing to worry about from a user's standpoint (which I admit might seem confusing).

The Error messages `CRIT Supervisor running as root (no user in config file)` stems from us running `supervisord` in the Docker container (not connected to whether Docker is started as root or not on your local machine! So you have to continue running Docker as a root on your machine/server or [add the docker user group to your user](https://docs.docker.com/engine/install/linux-postinstall/)) without specifying a user in the config file, which `supervisord` doesn't see as best practice but doesn't cause any problems when ran inside a Docker container. 
We will fix this in the next release as this might be highly misleading for a user as it implies that something went wrong even though everything worked fine.
The same applies for the second CRIT message.

Usually OCR4all should have been reachable on port 1476 (so e.g. `localhost:1476/ocr4all`) after you ran in the code in the first screenshot. Were you able to access OCR4all afterwards?

**Comment by svetlinsem** [comment]
Thank you for the information. Unfortunately, nothing happens after this text do I have to wait until i have any output?
I try to access myip:1476/ocr4all but not working.

**Comment by maxnth** [comment]
>Unfortunately, nothing happens after this text do I have to wait until i have any output?

The container should be up and running after the output in your first screenshot.
The container should also be reachable as long as the  `docker run` command isn't manually terminated (or automatically if something went horribly) or – when using `docker start <containername>` – as long as the container isn't stopped (can be checked with `docker ps -a`).

>I try to access myip:1476/ocr4all but not working.

Sadly I'm not familiar with Alibabacloud but is it possible that you have to allow port forwarding for the chosen port if you haven't already?

Does running `curl localhost:1476` or `curl localhost:1476/ocrall` in your shell while connected to your Alibabacloud instance (OCR4all container has to be up and running as well) return any HTML at all?

**Comment by svetlinsem** [comment]
Yes i have html on curl localhost:1476 but i can't connect.

**Comment by maxnth** [comment]
>Yes i have html on curl localhost:1476 but i can't connect.

That means that the OCR4all docker container is indeed running as expected and the problem is related to accessing certain ports on an Alibabacloud ECS instance. 

If setting up port forwarding isn't an option, using port `80` might help as that one is open by default for most cloud instances/virtual private servers.

Sadly I can't provide any concrete assistance on setting up OCR4all on an Alibabacloud ECS instance as German accounts seemingly aren't eligible for their free trial system.

**Comment by svetlinsem** [comment]
Thanks for the support. I think is port problem i will test and share the results.

**Comment by Lier007** [comment]
@svetlinsem  Have you solved it? I ran into the same problem on my own local machine. So do port 80

**Comment by Lier007** [comment]
“curl localhost:80” OK!

"curl localhost:80/ocrall" as follows
![image](https://user-images.githubusercontent.com/12529162/88877466-176a0300-d258-11ea-8ccd-915edbe0cc13.png)

**Comment by Kolophonium0** [comment]
Hey,
There is a typo:
It should be localhost:port/ocr4all.
________________________________
