### ISSUE TITLE
Infering on new pages

### ISSUE THREAD

**Issue by sathish331977** [OCR4all/getting_started#7]
Once the training is complete how to evaluate the trained model on new book/pages.

**Comment by maxnth** [comment]
After the training finished successfully the model(s) should be available in the `Recognition` tab. To evaluate you need to run the recognition on your test set, create GT for the test set and then evaluate the pages of your test set in the `Evaluation` tab.

**Comment by sathish331977** [comment]
Thank you @maxnth.
When you say create  a GT  (ground truth) for test set, does it mean i need to run all the process upto recognition on a different book.
My understanding of OCR4all might not be right, here is what i did.
Step 1. I took a pdf file (say a.pdf) and ran it through ocr4all and trained a model. Results of the file trained were good.
Step 2 . I want to apply the trained model to a new file (b.pdf) and capture the results.
My end goal is to use the trained model on different pdfs to get text files as output.

**Comment by maxnth** [comment]
>When you say create a GT (ground truth) for test set, does it mean i need to run all the process upto recognition on a different book.

I probably misunderstood what you meant by "evaluate" and thought that you wanted the character error rate/confusion matrix for new books/pages when using the models you trained with OCR4all. For that you'd need some ground truth to evaluate the model.
 
>Step 1. I took a pdf file (say a.pdf) and ran it through ocr4all and trained a model. Results of the file trained were good.
Step 2 . I want to apply the trained model to a new file (b.pdf) and capture the results.
My end goal is to use the trained model on different pdfs to get text files as output.

In that case (and if I understand the use case correctly) creating one/several new projects with your PDF files and simply running the OCR4all workflow (+ selecting the priorly trained models in the `Recognition` settings) should yield you the desired output.
