### ISSUE TITLE
Style and footnotes

### ISSUE THREAD

**Issue by jpb-badw** [OCR4all/getting_started#8]
The text I’m using contains such kind of text. Does OCR4all/LAREX have an option to recognize them? Do I have to get a specific model? 

- **small numbers**

![image](https://user-images.githubusercontent.com/73533526/98529327-c4074800-227d-11eb-894e-c24bc395d7c0.png)

- **Footnote referencing**

![image](https://user-images.githubusercontent.com/73533526/98529685-311add80-227e-11eb-9518-4a83944a04a3.png)

- **small letters**

![image](https://user-images.githubusercontent.com/73533526/98529341-c7023880-227d-11eb-98f8-8135e4fbe1ad.png)

- **Italics**

![image](https://user-images.githubusercontent.com/73533526/98529459-ed27d880-227d-11eb-9540-9a53a691f2dc.png)

**Comment by maxnth** [comment]
Testing the `idiotikon` model ensemble (available [here](https://github.com/Calamari-OCR/calamari_models)) might be worth a try.
Otherwise creating ground truth for lines where these kind of problems appear and fine tuning one of the available model(s) should also improve the performance.

**Comment by jpb-badw** [comment]
I tried the `idiotikon` model and I got way better "out of the box" results with the text. Is it anyhow possible that in the PageXML output, the fontsize, the style (italics) and the type (Arial,Times New Roman, etc) get recognized?

**Comment by maxnth** [comment]
>Is it anyhow possible that in the PageXML output, the fontsize, the style (italics) and the type (Arial,Times New Roman, etc) get recognized?

Sadly not at the moment but it might get added in one of the upcoming releases.
